### ISSUE TITLE
!!!!!!!can't use Chinese in chat sidebar

### ISSUE THREAD

**Issue by HMcode-tech** [continuedev/continue#1102]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://continue.dev/docs/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: W10
- Continue: 0.42
- IDE: Intellij IDEA 2023+
```

### Description

can't use Chinese in chat sidebar, and if you input Chinese, it can't be identified correctly.

**Comment by sestinj** [comment]
@HMcode-tech thank you for the report! I will take a look and try to include a fix for the next release

**Comment by ruaingchaisuang** [comment]
@sestinj Can you Chinese the whole thing or add a Chinese version?

**Comment by sestinj** [comment]
I think this is now solved as of multiple releases ago: @HMcode-tech can you confirm that this is no longer a problem?

**Comment by shenghai** [comment]
I'm meet the same issue in MacOS, after "add to chat", I can not input Chinese Characters into sidebar, My workaround is input Chinese Characters first, then "add to chat", but it feels very noisy.
love continue

**Comment by renlei-leon** [comment]
- OS: CentOS7.9
- Continue: 1.08
- IDE: Intellij IDEA 2022.3

Still have this problem, cann't input Chinse in chat box.
