### ISSUE TITLE
Cmd-v in the chat box will repeat the copied text multiple times

### ISSUE THREAD

**Issue by LeonardoGentile** [continuedev/continue#1246]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS:Mac Os 13.6.6
- Continue: 0.9.125
- IDE: VsCode 1.87.2
```

### Description

When pasting into the chat box with Cmd-V the pasted text will be repeated

### To reproduce

- Copy something from vscode of from anywhere else with Cmd-C, for example `this is a test`
- Pasting into the chat box with Cmd-v
Will paste the copied item multiple times, producing something like this

```
This is a testThis is a testThis is a testThis is a testThis is a testThis is a testThis is a testThis is a test
```
If I right click and select paste then the problem is not present and the text is pasted normally as expected

**Comment by sestinj** [comment]
Looks related to [this recent fix](https://github.com/continuedev/continue/issues/1081#issuecomment-2091617880)

**Comment by sestinj** [comment]
Appears resolved with preventDefault: https://github.com/continuedev/continue/commit/8117abcd7158c680327974882881721737369701.

I'll wait to close the issue until this is published in pre-release

**Comment by LeonardoGentile** [comment]
Hello @sestinj thanks for the quick fix! 
I've installed continue@0.9.129 that it should in theory solve the issue but it's still happening for me

**Comment by deansher** [comment]
I'd like to second that this is a hugely important bug. Not QUITE a blocker. But pretty close.

**Comment by sestinj** [comment]
Yup I'm seeing it too now. Working on a real fix, I'll update soon

**Comment by sestinj** [comment]
Ok finally figured out that it was pasting once per open input box. Silly mistake, but fixed here: https://github.com/continuedev/continue/commit/c3fd16bd9d666b8bfed8025fd7a45fe73139ca25, on its way in 0.9.132
