### ISSUE TITLE
Can't get past the "Use your API key" screen, must select "Local models"

### ISSUE THREAD

**Issue by dandv** [continuedev/continue#1605]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [ ] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: Linux
- Continue: 0.0.50
- IDE: PyCharm, WebStorm
```

### Description

After installing the plugin, it was impossible to "Continue" with the "Use your API key" option. Clicking on "Continue" after selecting that box, appeared to reload the page.

![image](https://github.com/continuedev/continue/assets/33569/da1b79d4-0a6a-4a99-afc7-ae5f10591034)

### To reproduce

1. Install the plugin
2. Press Ctrl+J (I was following the tutorial)
3. Click "Use your API key"
4. Click <kbd>Continue</kbd>

### Screencast

[Can't get past the USe Your API key screen.webm](https://github.com/continuedev/continue/assets/33569/8531e077-7765-433b-a2a9-57b439a8fab7)

**Comment by sestinj** [comment]
This was solved with the addition of this useEffect: https://github.com/continuedev/continue/blob/dev/gui/src/pages/onboarding/Onboarding.tsx#L29-L32

As with other JetBrains issues, I'll wait to close this until the new version is released

**Comment by dandv** [comment]
Still seeing this with v0.0.53 in PyCharm..

![image](https://github.com/user-attachments/assets/307730af-bffd-47ba-80ba-ba65c03a92b9)
