### ISSUE TITLE
highlight code error

### ISSUE THREAD

**Issue by LizhenQiangCOOL** [continuedev/continue#2025]
### Before submitting your bug report

- [ ] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [x] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: window11
- Continue: v0.9.197 (pre-release)
- IDE: vscode
- Model: ollama3.1:8b
- config.json:
  
{
  "models": [
    {
      "title": "Ollama",
      "provider": "ollama",
      "model": "AUTODETECT",
      "apiBase": "http://172.16.10.202:11434"
    },
    {
      "title": "Llama3.1",
      "model": "ollama3.1",
      "apiBase": "http://172.16.10.202:11434",
      "provider": "ollama"
    }
  ],
  "customCommands": [
    {
      "name": "test",
      "prompt": "{{{ input }}}\n\nWrite a comprehensive set of unit tests for the selected code. It should setup, run tests that check for correctness including important edge cases, and teardown. Ensure that the tests are complete and sophisticated. Give the tests just as chat output, don't edit any file.",
      "description": "Write unit tests for highlighted code"
    }
  ],
  // tab
  "tabAutocompleteModel": {
    "title": "Starcoder2 7b",
    "provider": "ollama",
    "model": "starcoder2:7b",
    "apiBase": "http://172.16.10.202:11434"
  },
  "embeddingsProvider": {
    "provider": "ollama",
    "model": "nomic-embed-text",
    "apiBase": "http://172.16.10.202:11434"
  },
  "contextProviders": [
    {
      "name": "code",
      "params": {}
    },
    {
      "name": "docs",
      "params": {}
    },
    {
      "name": "diff",
      "params": {}
    },
    {
      "name": "terminal",
      "params": {}
    },
    {
      "name": "problems",
      "params": {}
    },
    {
      "name": "folder",
      "params": {}
    },
    {
      "name": "codebase",
      "params": {}
    }
  ],
  "slashCommands": [
    {
      "name": "edit",
      "description": "Edit selected code"
    },
    {
      "name": "comment",
      "description": "Write comments for the selected code"
    },
    {
      "name": "share",
      "description": "Export the current chat session to markdown"
    },
    {
      "name": "cmd",
      "description": "Generate a shell command"
    },
    {
      "name": "commit",
      "description": "Generate a git commit message"
    }
  ],
  "requestOptions": {}
}
```

### Description

I highlighted the code but it didn't work.

![image](https://github.com/user-attachments/assets/b9b26b26-4a7a-41d2-b5b7-5351e09eb58c)

![image](https://github.com/user-attachments/assets/3d38c69e-46eb-4dea-afa3-229509d3d383)

NO Slash Commands Edit，it work

![image](https://github.com/user-attachments/assets/75a25c05-5644-4afe-a35e-0e67684a7637)

**Comment by Patrick-Erichsen** [comment]
Hi @LizhenQiangCOOL , this should be solved in the most recent pre-release, `v0.9.197`. Are you sure that's the current version you're on? A restart of VS Code would be a good way to confirm you're actually running `v0.9.197`.

**Comment by cr-zhichen** [comment]
Hi @Patrick-Erichsen 

I'm also encountering the same issue with the highlighted code not working. I'm using version v0.9.197 (pre-release), and I've tried restarting VS Code, but the problem persists. Could you please advise on what else I can try or if there are any additional steps I should take? If there's any specific information or logs you need from me to help troubleshoot this issue, just let me know.

Thank you!

![66c6b9deee3b7.png](https://img-cdn.ccrui.cn/2024/08/22/66c6b9deee3b7.png)
![66c6b4b8b733e.png](https://img-cdn.ccrui.cn/2024/08/22/66c6b4b8b733e.png)

**Comment by LCorleone** [comment]
v0.9.198 is ok

**Comment by cr-zhichen** [comment]
> v0.9.198 is ok

I've updated to version v0.9.198, and the issue is now resolved. Thanks for your help!

**Comment by LizhenQiangCOOL** [comment]
I'm sure this has been fixed in version v0.9.199 (pre-release), thanks to everyone for helping, God bless you all
