### ISSUE TITLE
version-0.0.80  This version is unable to copy the content of the clipboard into the chat, which is very frustrating.

### ISSUE THREAD

**Issue by yinshaoqian** [continuedev/continue#2853]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [ ] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [ ] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS:
- Continue version:
- IDE version:
- Model:
- config.json:
```

### Description

version-0.0.80  This version is unable to copy the content of the clipboard into the chat, which is very frustrating,
And it is also not possible to cut the text content that has already been entered.

### To reproduce

version-0.0.80  This version is unable to copy the content of the clipboard into the chat, which is very frustrating,
And it is also not possible to cut the text content that has already been entered.

**Comment by Patrick-Erichsen** [comment]
Mind sharing what OS you are on? This has been an issue for non-Mac OS' but should be resolved in our next release.

**Comment by Altroo** [comment]
I can confirm this issue as well, in my pycharm, windows 11.

**Comment by Altroo** [comment]
@Patrick-Erichsen bug still present in 0.0.81, can't shortcut copy paste on windows.

**Comment by richardbowman** [comment]
Same here on Windows 11, have to hand select blocks and then copy manually, the copy shortcut button does nothing. Also, the Insert At Cursor does nothing as well.

**Comment by phntm7** [comment]
Had the same problem. Disabling "Advanced Paste" in Windows PowerToys helped in my case

**Comment by RomneyDa** [comment]
@yinshaoqian can you verify that this has been resolved on a newer release e.g.  `0.0.90`?

**Comment by sestinj** [comment]
this appears to have been solved. please re-open if still experiencing!
