### ISSUE TITLE
Hitting `esc` in Edit session doesn't reject pending diffs

### ISSUE THREAD

**Issue by Patrick-Erichsen** [continuedev/continue#3186]
### Before submitting your bug report

- [ ] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [ ] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [ ] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### To reproduce

- Use Edit
- Hit the `esc` key either in the editor or TipTap
- Confirm that pending diffs are not closed out (they should be rejected)

**Comment by RomneyDa** [comment]
@Patrick-Erichsen this is resolved now?

**Comment by Patrick-Erichsen** [comment]
I'm not sure actually. I'm working on Edit this week so I will confirm and fix it it's still an issue 👍

**Comment by RomneyDa** [comment]
Looks like this has been resolved
