### ISSUE TITLE
When using LM Studio, AutoComplete prompts an error: inputConfig required to render jinja prompt.

### ISSUE THREAD

**Issue by yarin-zhang** [continuedev/continue#3614]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [ ] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: macOS 15.1 (24B83)
- Continue version: 0.8.66 - 2024-12-20
- IDE version: VSCode 1.91.1
- Model: StarCoder2-3b
- config.json:
  
"models": [
	{
	"model": "StarCoder-3b",
	"provider":"lmstudio",
	"apiBase": "http://127.0.0.1:1234/v1",
	"title": "StarCoder2"
	}
],
"tabAutocompleteModel": {
	"title": "StarCoder-3b-lmstudio",
	"model": "StarCoder-3b",
	"apiBase": "http://127.0.0.1:1234/v1/",
	"completionOptions": {},
	"provider": "lmstudio"
},
```

### Description

When I use Continue with LM Studio, the Chat feature is already functioning properly. However, the tabAutocomplete feature is not working. It always prompts an error.

```
[ERROR] 
inputConfig required to render jinja prompt. Error Data: n/a, Additional Data: n/a
```

### To reproduce

1. Start server in LM Studio.
2. Edit config.json .
3. Press `Tab` in File.

### Log output

```Shell
LM Studio Log


2025-01-06 10:33:58  [INFO] 
[LM STUDIO SERVER] Running completion on text: [Hidden]
2025-01-06 10:33:58  [INFO] 
Streaming response..
2025-01-06 10:33:58  [INFO] 
[LM STUDIO SERVER] Processing...
2025-01-06 10:33:58 [DEBUG] 
1 Error predicting: Error: inputConfig required to render jinja prompt
    at /Applications/LM Studio.app/Contents/Resources/app/.webpack/lib/llmworker.js:10:36393
    at async t.formatPrompt (/Applications/LM Studio.app/Contents/Resources/app/.webpack/lib/llmworker.js:10:34152)
    at async t.getContextOverflowPolicy (/Applications/LM Studio.app/Contents/Resources/app/.webpack/lib/llmworker.js:10:49563)
    at async t.temp_createLlamaPredictionArgs (/Applications/LM Studio.app/Contents/Resources/app/.webpack/lib/llmworker.js:8:366412)
    at async t.LLMEngineWrapper.predictTokens (/Applications/LM Studio.app/Contents/Resources/app/.webpack/lib/llmworker.js:10:26226)
    at async Object.predictTokens (/Applications/LM Studio.app/Contents/Resources/app/.webpack/lib/llmworker.js:15:7181)
    at async Object.handleMessage (/Applications/LM Studio.app/Contents/Resources/app/.webpack/lib/llmworker.js:15:1129)
2025-01-06 10:33:58 [ERROR] 
inputConfig required to render jinja prompt. Error Data: n/a, Additional Data: n/a
2025-01-06 10:33:58  [INFO] 
[LM STUDIO SERVER] Client disconnected. Stopping generation..
2025-01-06 10:38:59  [INFO] 
Server stopped.
```

VSCode Log

```
6console.ts:137 [Extension Host] Error generating autocompletion:  Error: request to http://127.0.0.1:1234/v1/completions failed, reason: connect ECONNREFUSED 127.0.0.1:1234
	at customFetch2 (/Users/yarinz/.vscode/extensions/continue.continue-0.8.66-darwin-arm64/out/extension.js:108288:19)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async withExponentialBackoff (/Users/yarinz/.vscode/extensions/continue.continue-0.8.66-darwin-arm64/out/extension.js:104133:26)
	at async LMStudio._legacystreamComplete (/Users/yarinz/.vscode/extensions/continue.continue-0.8.66-darwin-arm64/out/extension.js:108950:26)
	at async LMStudio._streamChat (/Users/yarinz/.vscode/extensions/continue.continue-0.8.66-darwin-arm64/out/extension.js:108967:28)
	at async LMStudio._streamComplete (/Users/yarinz/.vscode/extensions/continue.continue-0.8.66-darwin-arm64/out/extension.js:108918:26)
	at async LMStudio.streamComplete (/Users/yarinz/.vscode/extensions/continue.continue-0.8.66-darwin-arm64/out/extension.js:108413:30)
	at async ListenableGenerator._start (/Users/yarinz/.vscode/extensions/continue.continue-0.8.66-darwin-arm64/out/extension.js:113751:28)
```
```

**Comment by SemafonKA** [comment]
Seems like there is an issue in LM Studio 0.3.6-6+ beta builds (https://github.com/lmstudio-ai/lmstudio-bug-tracker/issues/282). At beta 0.3.6-5 all works as supposed.

**Comment by yarin-zhang** [comment]
It's great to see someone reporting the related error.

For reference, my LM Studio Version is 0.3.6.

**Comment by yarin-zhang** [comment]
It has been confirmed to be an issue with LM Studio, which has been resolved in version 0.3.6 build 8.∑

**Comment by Universeal13** [comment]
i still have the error 
Error rendering prompt with jinja template: TypeError: Cannot read properties of undefined (reading 'type'). Error Data: n/a, Additional Data: n/a

**Comment by SatishSyamu** [comment]
I am using LM Studio 0.3.9 and I still facing this issue "
Error rendering prompt with jinja template: SyntaxError: Unknown statement type: Identifier. Error Data: n/a, Additional Data: n/a"

Anyone please help to resolve this issue.

**Comment by CicadaDigital** [comment]
Same issue on 0.3.10 ...

**Comment by DavoodHakimi** [comment]
same issue on 0.3.10 (build 6) with `DevQuasar/CohereForAI.c4ai-command-r7b-12-2024-GGUF`
`
Error rendering prompt with jinja template: SyntaxError: Unknown statement type: Identifier
`
