### ISSUE TITLE
the /commit action does not work anymore

### ISSUE THREAD

**Issue by robertoranon** [continuedev/continue#4860]
### Before submitting your bug report

- [x] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [x] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [x] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS:
- Continue version:
- IDE version:
- Model:
- config:
  

  
  OR link to assistant in Continue hub:
```

### Log output

```Shell

```

**Comment by ingo-eichhorst** [comment]
Having the same issue: v. 1.1.17, VS-Code, Mac

**Comment by debrsky** [comment]
1.1.18 Fixed

**Comment by juanfcocontreras** [comment]
> 1.1.18 Fixed

It seems that the custom commands have been fixed, but not the predefined slash commands by default like /commit. At least for me, the ones I have defined do work with version 1.1.18 but /commit does not appear:

![Image](https://github.com/user-attachments/assets/63943ec2-d532-40be-9413-bab2ddfb594d)

**Comment by RomneyDa** [comment]
@pranavgaikwad @juanfcocontreras are you using YAML or any assistant that isn't the JSON? JSON config is ignored if using yaml assistants

**Comment by juanfcocontreras** [comment]
> [@pranavgaikwad](https://github.com/pranavgaikwad) [@juanfcocontreras](https://github.com/juanfcocontreras) are you using YAML or any assistant that isn't the JSON? JSON config (including config.ts) is ignored if using yaml assistants

I'm just using JSON config, I haven't updated to YAML yet. Should I?

**Comment by ingo-eichhorst** [comment]
Tried YAML, but slash is not supported by yaml config. The docs say we can (or should?) use prompts:
![Image](https://github.com/user-attachments/assets/f5372ffe-9e28-4ba0-a090-0a377cd42811)
https://docs.continue.dev/customize/tutorials/build-your-own-slash-command

In this case it works, but for more complex scenarios prompt files are not enough.

However, here is the prompt file for the commit message. Simply drop it in .continue/prompts or use a Block in continue hub like: https://hub.continue.dev/raffb/conventional-commits

```md
name: Commit Message
description: Create a commit message for the latest changes
---

For the following diff, provide a commit message:

@diff
```

**Comment by ingo-eichhorst** [comment]
> So the prompt for the commit will no longer be integrated into continue?
> 
> If so, can someone share the exact prompt that was in previous versions where it was integrated to do exactly the same?

Not sure if it's going to be removed. Maybe it's just not added ❓❗  
But here is the complete code: https://github.com/continuedev/continue/blob/main/core/commands/slash/commit.ts#L16

**Comment by juanfcocontreras** [comment]
@ingo-eichhorst I am trying to make the commit command work with a prompt file. First, I migrated all my configuration from json to yaml, and then I created a prompt with the following code:

```
name: commit
description: Create a commit message for the latest changes
---

@diff

Generate a commit message for the above set of changes. First, give a single sentence, no more than 80 characters. Output nothing except for the commit message, and don't surround it in quotes.
```

However, it does not seem to be interpreting @diff correctly, because it gives me a generic message on how to generate messages for commits:

> Preparing to commit changes
To commit your changes, I need to understand what files have been modified and what you want to include in the commit. Let me help you through the commit process: [...]

I tried adding the following code to `config.yaml`, but the result is the same:

```
context:
  - provider: diff
```

I have tried both with staged code and unstaged code.

Any more ideas on what I have to do?

**Comment by ingo-eichhorst** [comment]
> This seems to be resolved in the latest beta versions, I was testing with the stable one (1.0.5)
> 
> > [@ingo-eichhorst](https://github.com/ingo-eichhorst) I am trying to make the commit command work with a prompt file. First, I migrated all my configuration from json to yaml, and then I created a prompt with the following code:
> > ```
> > name: commit
> > description: Create a commit message for the latest changes
> > ---
> > 
> > @diff
> > 
> > Generate a commit message for the above set of changes. First, give a single sentence, no more than 80 characters. Output nothing except for the commit message, and don't surround it in quotes.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > However, it does not seem to be interpreting @diff correctly, because it gives me a generic message on how to generate messages for commits:
> > > Preparing to commit changes
> > > To commit your changes, I need to understand what files have been modified and what you want to include in the commit. Let me help you through the commit process: [...]
> > 
> > 
> > I tried adding the following code to `config.yaml`, but the result is the same:
> > ```
> > context:
> >   - provider: diff
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I have tried both with staged code and unstaged code.
> > Any more ideas on what I have to do?

OK, I was on 1.1.22 earlier today

**Comment by getfit-us** [comment]
so question is this resolved in any version? I was looking to post a bug about this today. I use config.ts to add custom commands also with context.

**Comment by ingo-eichhorst** [comment]
> so question is this resolved in any version? I was looking to post a bug about this today. I use config.ts to add custom commands also with context. 

It's not resolved. Slash commands are not workng in current versions (stable 1.0.5 and pre-release 1.1.22)

**Comment by tomasz-stefaniak** [comment]
> > so question is this resolved in any version? I was looking to post a bug about this today. I use config.ts to add custom commands also with context.
> 
> It's not resolved. Slash commands are not workng in current versions (stable 1.0.5 and pre-release 1.1.22)

Slash commands are deprecated. They may still work in config.json but do not work in config.yaml.

**Comment by ingo-eichhorst** [comment]
> > > so question is this resolved in any version? I was looking to post a bug about this today. I use config.ts to add custom commands also with context.
> > 
> > 
> > It's not resolved. Slash commands are not workng in current versions (stable 1.0.5 and pre-release 1.1.22)
> 
> Slash commands are deprecated. They may still work in config.json but do not work in config.yaml.

How to compensate for that? What alternatives to slash-commands do we have?

**Comment by tomasz-stefaniak** [comment]
Right now context providers are not supported in custom prompts but we'd be interested in hearing more about how you'd like to use context providers in prompts, so we can figure out our plan longer term.

You are able to invoke custom prompts with /. There are two solutions you can use at the moment. Probably the most effective way is to use custom prompts with agent mode so that the model can invoke tools as needed. The prompt can even suggest to the agent to use a specific tool or to search a specific directory etc. 

Alternatively, you can create a string-only custom prompt and then @ the context provider when using it (e.g. `/commit @diff`).
