### ISSUE TITLE
Promts/CustomCommands not worked at all

### ISSUE THREAD

**Issue by emzaedu** [continuedev/continue#5245]
### Before submitting your bug report

- [x] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [x] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [x] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown

```

### Description

This is what happens, it doesn't pass at all the part of the code that was added to the context; instead, it only sends a prompt and nothing.

![Image](https://github.com/user-attachments/assets/bb7edb8b-43e3-48b9-bf0a-c6c9f0409ef2)

### Log output

```Shell

```

**Comment by bhadrik-infivr** [comment]
![Image](https://github.com/user-attachments/assets/6de06a8d-6a7c-4a5e-8499-6fba3a6440e3)

Same issue also clicking on the prompt open up prompt file which is completely empty.

**Comment by RomneyDa** [comment]
@bhadrik-infivr @emzaedu all issues here should be fixed by https://github.com/continuedev/continue/pull/5946

**Comment by emzaedu** [comment]
The issue where context inserted via CTRL+L and the use of prompts (such as /explain) is not recognized still persists in the latest release.
The bug occurs with YAML configuration — everything works correctly with JSON.
