### ISSUE TITLE
Menu is unreadable in VSCode dark mode

### ISSUE THREAD

**Issue by alexander-potemkin** [continuedev/continue#743]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://continue.dev/docs/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: MacOS Sonoma 14.2.1 (23C71)
- Continue: 0.8.1
```

### Description

Options menu is transparent - can't see the actual proposals. Please, see screenshot.

### To reproduce

1. Open Continue
2. Enter `/`
3. 
<img width="256" alt="Screenshot 2024-01-11 at 12 11 27" src="https://github.com/continuedev/continue/assets/2323840/d76fc386-7c41-4472-b3b1-167aa740661a">

### Log output

```Shell
Nothing in console
```

**Comment by sestinj** [comment]
@alexander-potemkin My understanding is that this happened because the VS Code theme had a transparent color. I just made a change in 0.9.13 pre-release so that any alpha channel will be stripped out of the color that we use. Can you confirm that things are looking better or is it still transparent?

**Comment by alexander-potemkin** [comment]
Thanks for the prompt response! @sestinj , unfortunately, I can't tell yes or now - as pre-release version just never finishes loading... =/

**Comment by sestinj** [comment]
@alexander-potemkin Assuming this was version 0.9.16 and you are on Apple Silicon, this infinite loading problem is solved in 0.9.17. Sorry about that!

And more improved theme matching in the near future!

**Comment by alexander-potemkin** [comment]
Yes, you were correct, and thank you for such a prompt fix! It works like a charm now!

**Comment by ashutoshsaboo** [comment]
hey @sestinj , i'm still facing this exact same issue in Cursor. I'm on the latest version of Continue.dev extension, can you please check on what's going wrong?
