### ISSUE TITLE
Header is not defined  error

### ISSUE THREAD

**Issue by jingwanha** [continuedev/continue#802]
### Before submitting your bug report

- [ ] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [ ] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [ ] I've seen the [troubleshooting guide](https://continue.dev/docs/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
HOST OS: Window
SERVER OS : Ubuntu
Continue: v0.9.41
IDE: VSCode 1.80.1
```

### Description

I run codellama7b on docker(ollama) on ubuntu server.
Then, try to use in vscode with continue on window

When I run the command, an error message saying "header is not defined"
like below attached image

![err_msg](https://github.com/continuedev/continue/assets/76804517/9e9975b2-de76-466e-8b7d-e7462d05dd6b)

![Uploading err_msg.jpg…]()

**Comment by sestinj** [comment]
@jingwanha would you mind clicking the "Show Logs" button and sharing the full error that appears in the console? It would also help me debug if you could share your `config.json`.

**Comment by jingwanha** [comment]
@sestinj 
This is error page of "Show Logs"
![Uploading log.jpg…]()

**Comment by unreal-wind** [comment]
@jingwanha Try upgrading Visual Studio Code to the latest version. I encountered the same error, and it was resolved after upgrading.

**Comment by sestinj** [comment]
@jingwanha everything in your config looks correct, so I do think that unreal-wind's suggestion is probably the solution. Let me know if not!

**Comment by jingwanha** [comment]
@unreal-wind @sestinj Thanks for your help.
I updated both vscode and continue plugin versions, but I'm still getting the error.
(VSCODE : 1.80.1 -> 1.86.0)
(Continue Plugin : v0.9.41 -> v0.9.43)

![error](https://github.com/continuedev/continue/assets/76804517/5981ec18-30af-49c2-99dd-a92e2101fe21)
![show_logs](https://github.com/continuedev/continue/assets/76804517/a2ec675a-81e8-4b53-b689-60ac22fb8f96)
